name: Testingtestingtesting
favicon: null
layout_spectrum: 0.24905988946557045
typography_spectrum: 0.6240674261935055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7613226759713143
  lightness: 0.8077268863562495
  saturation: 0.4731514777522534
  rhythmicContrast: 0.018113633152097464
purpose: []
